"""持久化端口协议。服务只依赖该协议，具体实现见 adapters。"""

from __future__ import annotations

from typing import ContextManager, Protocol

from ..domain import entities as e


class Repository(Protocol):
    # 事务串行化：批量准入、结算过账等原子过程在同一把锁内完成
    def transaction(self) -> ContextManager[None]:
        ...

    # 链路
    def save_link(self, link: e.Link) -> None: ...
    def get_link(self, code: str) -> e.Link | None: ...
    def list_links(self) -> list[e.Link]: ...

    # 租户
    def save_tenant(self, tenant: e.Tenant) -> None: ...
    def get_tenant(self, code: str) -> e.Tenant | None: ...
    def list_tenants(self) -> list[e.Tenant]: ...

    # 维护窗口
    def add_maintenance(self, window: e.MaintenanceWindow) -> None: ...
    def list_maintenance(self, link_code: str | None = None) -> list[e.MaintenanceWindow]: ...

    # 预约
    def add_reservation(self, reservation: e.Reservation) -> None: ...
    def get_reservation(self, code: str) -> e.Reservation | None: ...
    def list_reservations(self, tenant_code: str | None = None) -> list[e.Reservation]: ...
    def update_reservation(self, reservation: e.Reservation) -> None: ...

    # 批量结果
    def save_batch(self, result: e.BatchResult) -> None: ...
    def get_batch(self, code: str) -> e.BatchResult | None: ...

    # 遥测（多版本保留）
    def upsert_telemetry(self, sample: e.TelemetrySample) -> None: ...
    def get_telemetry(self, link_code: str, bucket_ts: int) -> e.TelemetrySample | None: ...
    def list_telemetry_versions(self, link_code: str, bucket_ts: int) -> list[e.TelemetrySample]: ...
    def list_telemetry(self, link_code: str) -> list[e.TelemetrySample]: ...

    # 事件
    def add_incident(self, incident: e.Incident) -> None: ...
    def get_incident(self, code: str) -> e.Incident | None: ...
    def list_incidents(self, status: e.IncidentStatus | None = None) -> list[e.Incident]: ...
    def update_incident(self, incident: e.Incident) -> None: ...

    # 处置动作
    def add_action(self, action: e.ReservationAction) -> None: ...
    def list_actions(
        self, incident_code: str | None = None, reservation_code: str | None = None
    ) -> list[e.ReservationAction]: ...

    # 补偿
    def get_compensation(self, idempotency_key: str) -> e.Compensation | None: ...
    def add_compensation(self, comp: e.Compensation) -> None: ...
    def update_compensation(self, comp: e.Compensation) -> None: ...
    def list_compensations(self, incident_code: str | None = None) -> list[e.Compensation]: ...

    # 账本
    def has_ledger_entry(self, idempotency_key: str) -> bool: ...
    def add_ledger_entry(self, entry: e.LedgerEntry) -> None: ...
    def list_ledger(self, period: str | None = None, tenant_code: str | None = None) -> list[e.LedgerEntry]: ...

    # 账期
    def get_or_create_period(self, period: str) -> e.AccountingPeriod: ...
    def update_period(self, period: e.AccountingPeriod) -> None: ...
    def list_periods(self) -> list[e.AccountingPeriod]: ...
